# Generated by Django 5.2.1 on 2025-05-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemExtra',
        ),
    ]
