# Generated by Django 5.2.1 on 2025-05-23 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Unknown Customer', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='0000000000', help_text='Ghanaian phone number in format +233XXXXXXXXX or 0XXXXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in format '+233XXXXXXXXX' or '0XXXXXXXXX'.", regex='^(\\+233|0)\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.TextField(blank=True, help_text='Required for delivery orders, leave blank for pickup'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Pickup', max_length=10),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
