# Generated by Django 5.2.1 on 2025-05-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='Link to the main item if this is an extra.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='orders.orderitem'),
        ),
    ]
