# Generated by Django 5.2.1 on 2025-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_parent_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, choices=[('Adenta', 'Adenta'), ('Accra', 'Accra'), ('Madina', 'Madina'), ('Legon', 'Legon')], default='Accra', help_text='Select delivery location (Required for delivery orders).', max_length=50),
        ),
    ]
