# Generated by Django 5.2.1 on 2025-05-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, choices=[('Adenta', 'Adenta (Fee: ₵5.00)'), ('Accra', 'Accra (Fee: ₵7.00)'), ('Madina', 'Madina (Fee: ₵4.00)'), ('Legon', 'Legon (Fee: ₵3.00)')], default='Accra', help_text='Select delivery location (Required for delivery orders).', max_length=50),
        ),
    ]
