# Generated by Django 5.2.2 on 2025-06-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_delivery_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='parent_item',
        ),
    ]
