# Generated by Django 5.2.2 on 2025-06-17 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_orderitem_parent_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name (required for delivery orders)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Ghanaian phone number in format +233XXXXXXXXX or 0XXXXXXXXX (required for delivery orders)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format '+233XXXXXXXXX' or '0XXXXXXXXX'.", regex='^(\\+233|0)\\d{9}$')]),
        ),
    ]
