# Generated by Django 5.2.2 on 2025-06-23 19:29

from django.db import migrations


def populate_delivery_locations(apps, schema_editor):
    DeliveryLocation = apps.get_model('orders', 'DeliveryLocation')
    
    delivery_locations = [
        {'name': 'Accra Central', 'fee': 10.00, 'is_active': True},
        {'name': 'East Legon', 'fee': 15.00, 'is_active': True},
        {'name': 'Spintex', 'fee': 12.00, 'is_active': True},
        {'name': 'Tema', 'fee': 20.00, 'is_active': True},
        {'name': 'Kasoa', 'fee': 25.00, 'is_active': True},
        {'name': 'Kumasi', 'fee': 50.00, 'is_active': True},
        {'name': 'Tamale', 'fee': 75.00, 'is_active': True},
    ]
    
    for location_data in delivery_locations:
        DeliveryLocation.objects.create(**location_data)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_deliverylocation'),
    ]

    operations = [
        migrations.RunPython(populate_delivery_locations, reverse_code=migrations.RunPython.noop),
    ]
