# Generated by Django 5.2.2 on 2025-06-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_convert_delivery_location_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
