# Generated by Django 4.2.23 on 2025-07-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_alter_orderassignment_options_and_more'),
        ('orders', '0016_order_custom_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(blank=True, help_text='Select delivery location (Required for delivery orders unless custom location is provided).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.deliverylocation'),
        ),
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
    ]
