# Generated by Django 4.2.23 on 2025-07-14 15:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Historical delivery fee at time of order', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location_name',
            field=models.CharField(blank=True, help_text='Historical delivery location name at time of order', max_length=255, null=True),
        ),
    ]
