# Generated by Django 4.2.23 on 2025-07-14 15:46

from django.db import migrations


def populate_historical_delivery_data(apps, schema_editor):
    """Populate historical delivery location data for existing orders"""
    Order = apps.get_model('orders', 'Order')
    
    # Update orders that have a delivery location
    for order in Order.objects.filter(delivery_location__isnull=False):
        if order.delivery_location:
            order.delivery_location_name = order.delivery_location.name
            order.delivery_location_fee = order.delivery_location.fee
            order.save(update_fields=['delivery_location_name', 'delivery_location_fee'])
    
    # Update orders that have custom delivery location
    for order in Order.objects.filter(custom_delivery_location__isnull=False):
        if order.custom_delivery_location and not order.delivery_location_name:
            order.delivery_location_name = order.custom_delivery_location
            order.delivery_location_fee = order.custom_delivery_fee
            order.save(update_fields=['delivery_location_name', 'delivery_location_fee'])


def reverse_historical_delivery_data(apps, schema_editor):
    """Reverse the data migration"""
    Order = apps.get_model('orders', 'Order')
    Order.objects.update(delivery_location_name=None, delivery_location_fee=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_add_historical_delivery_location_fields'),
    ]

    operations = [
        migrations.RunPython(
            populate_historical_delivery_data,
            reverse_historical_delivery_data
        ),
    ]
