# Generated by Django 4.2.23 on 2025-07-14 15:55

from django.db import migrations

def populate_missing_delivery_history(apps, schema_editor):
    """Populate historical delivery data for orders missing it"""
    Order = apps.get_model('orders', 'Order')

    # Update orders with delivery location but missing historical data
    orders_missing_history = Order.objects.filter(
        delivery_location__isnull=False,
        delivery_location_name__isnull=True
    ).select_related('delivery_location')

    for order in orders_missing_history:
        if order.delivery_location and not order.delivery_location_name:
            order.delivery_location_name = order.delivery_location.name
            order.delivery_location_fee = order.delivery_location.fee
            order.save(update_fields=['delivery_location_name', 'delivery_location_fee'])

    # Update orders with custom delivery locations
    custom_orders_missing_history = Order.objects.filter(
        custom_delivery_location__isnull=False,
        delivery_location__isnull=True,
        delivery_location_name__isnull=True
    )

    for order in custom_orders_missing_history:
        if order.custom_delivery_location and not order.delivery_location_name:
            order.delivery_location_name = order.custom_delivery_location
            order.delivery_location_fee = order.custom_delivery_fee
            order.save(update_fields=['delivery_location_name', 'delivery_location_fee'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_fix_missing_delivery_history'),
    ]

    operations = [
        migrations.RunPython(populate_missing_delivery_history),
    ]
