# Generated by Django 4.2.23 on 2025-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_populate_delivery_names_from_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Accepted', max_length=20),
        ),
    ]
