# Generated by Django 5.2.1 on 2025-05-22 17:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('extra_type', models.CharField(choices=[('topping', 'Topping'), ('sauce', 'Sauce'), ('side', 'Side Dish'), ('drink', 'Drink'), ('other', 'Other')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_extras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extra Item',
                'verbose_name_plural': 'Extra Items',
                'ordering': ['extra_type', 'name'],
                'unique_together': {('name', 'extra_type')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_extras',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menu.extra'),
        ),
    ]
