# Generated by Django 5.2.1 on 2025-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0002_merge_extras_into_menuitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available_extras',
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['item_type', 'name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('regular', 'Regular Item'), ('extra', 'Extra Item')], default='regular', help_text='Whether this is a regular menu item or an extra', max_length=10),
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
