# Generated by Django 5.2.2 on 2025-07-05 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_merge_extras_into_menuitems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('regular', 'Regular Item'), ('extra', 'Extra Item')], db_index=True, default='regular', help_text='Whether this is a regular menu item or an extra', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['item_type', 'is_available'], name='menu_type_available_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available', 'item_type', 'name'], name='menu_available_type_name_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['created_at', 'item_type'], name='menu_created_type_idx'),
        ),
    ]
