# Generated by Django 4.2.23 on 2025-07-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_add_menu_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('regular', 'Regular Item'), ('extra', 'Extra Item'), ('bolt', 'Bolt Item'), ('wix', 'WIX Item')], db_index=True, default='regular', help_text='Type of menu item: regular, extra, bolt, or wix', max_length=10),
        ),
    ]
