# Generated by Django 5.2.1 on 2025-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'ordering': ['name'], 'verbose_name': 'Extra Item', 'verbose_name_plural': 'Extra Items'},
        ),
        migrations.AlterUniqueTogether(
            name='extra',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='extra',
            name='extra_type',
        ),
    ]
