# Generated by Django 4.2.23 on 2025-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_add_bolt_wix_item_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'item_type')},
        ),
    ]
