# Generated by Django 5.2.1 on 2025-01-14 01:00

from django.db import migrations, models

def convert_wix_to_regular(apps, schema_editor):
    """Convert all WIX items to regular items and remove WIX- prefix"""
    MenuItem = apps.get_model('menu', 'MenuItem')
    
    # Get all WIX items
    wix_items = MenuItem.objects.filter(item_type='wix')
    
    for item in wix_items:
        # Remove WIX- prefix if present
        original_name = item.name
        if item.name.startswith('WIX-'):
            item.name = item.name[4:]
        
        # Check if a regular item with this name already exists
        base_name = item.name
        counter = 1
        while MenuItem.objects.filter(name=item.name, item_type='regular').exists():
            item.name = f"{base_name} (WIX-{counter})"
            counter += 1
        
        # Change type to regular
        item.item_type = 'regular'
        item.save()
        
        if item.name != original_name:
            print(f"Converted WIX item '{original_name}' to regular item '{item.name}'")

def reverse_conversion(apps, schema_editor):
    """This migration is not reversible"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_unique_name_add_unique_together'),
    ]

    operations = [
        migrations.RunPython(convert_wix_to_regular, reverse_conversion),
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(
                choices=[('regular', 'Regular Item'), ('extra', 'Extra Item'), ('bolt', 'Bolt Item')],
                db_index=True,
                default='regular',
                help_text='Type of menu item: regular, extra, or bolt',
                max_length=10
            ),
        ),
    ]
