[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements-prod.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput --clear",
    "python manage.py migrate --noinput"
]

[start]
cmd = "bash railway_start.sh"
