# Generated by Django 5.2.1 on 2025-05-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', help_text='Type of transaction (Payment or Refund)', max_length=10),
        ),
    ]
