# Generated by Django 5.2.2 on 2025-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TELECEL CASH', 'Telecel Cash'), ('MTN MOMO', 'MTN MoMo'), ('PAYSTACK(USSD)', 'Paystack (USSD)'), ('PAYSTACK(API)', 'Paystack (API)')], default='CASH', max_length=20),
        ),
    ]
