# Generated by Django 4.2.x on 2025-01-14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_payments_pa_created_3147e3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wix_order_number',
            field=models.CharField(blank=True, help_text='Wix order number for payments made on Wix platform', max_length=100, null=True),
        ),
    ]
