# Generated by Django 4.2.23 on 2025-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_wix_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TELECEL CASH', 'Telecel Cash'), ('MTN MOMO', 'MTN MoMo'), ('PAYSTACK(USSD)', 'Paystack (USSD)'), ('PAYSTACK(API)', 'Paystack (API)'), ('PAID_ON_WIX', 'Paid on Wix')], default='CASH', max_length=20),
        ),
    ]
