# Generated by Django 5.2.1 on 2025-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(default='ADAUG-0000', editable=False, help_text='Auto-generated unique identifier for staff members (ADAUG-XXX)', max_length=10, unique=True, verbose_name='Staff ID'),
            preserve_default=False,
        ),
    ]
