# Generated by Django 5.2.2 on 2025-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('frontdesk', 'Frontdesk Staff'), ('kitchen', 'Kitchen Staff'), ('delivery', 'Delivery Staff')], default='frontdesk', help_text='User role determines access permissions', max_length=10, verbose_name='Role'),
        ),
    ]
