# Generated by Django 4.2.23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_remove_photo_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeliveryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('deliveries_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='deliveries.deliveryrider')),
            ],
            options={
                'verbose_name': 'Daily Delivery Stats',
                'verbose_name_plural': 'Daily Delivery Stats',
                'ordering': ['-date'],
                'indexes': [
                    models.Index(fields=['rider', 'date'], name='del_daily_rider_date_idx'),
                ],
                'unique_together': {('rider', 'date')},
            },
        ),
        migrations.AddField(
            model_name='deliveryrider',
            name='today_deliveries',
            field=models.IntegerField(default=0, help_text='Number of deliveries completed today'),
        ),
    ]
