# Generated by Django 4.2.23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_add_daily_delivery_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrider',
            name='rating',
        ),
    ]
