# Generated by Django 4.2.23 on 2025-07-12 11:15

from django.db import migrations, models
import django.utils.timezone
from decimal import Decimal
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_remove_performance_and_feedback'),
    ]

    operations = [
        # First, drop the existing table with wrong schema
        migrations.RunSQL(
            "DROP TABLE IF EXISTS deliveries_deliverylocation;",
            reverse_sql=""
        ),
        
        # Then create the DeliveryLocation model with correct schema
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the delivery location', max_length=100, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Delivery fee for this location', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is currently available for delivery')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Location',
                'verbose_name_plural': 'Delivery Locations',
                'ordering': ['name'],
            },
        ),
    ]
