# Generated by Django 4.2.23 on 2025-07-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_remove_commission_fee_proof_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderassignment',
            options={'ordering': ['-id']},
        ),
        migrations.RenameIndex(
            model_name='orderassignment',
            new_name='deliveries__status_ae3fa1_idx',
            old_name='deliveries__status_idx',
        ),
        migrations.RenameIndex(
            model_name='orderassignment',
            new_name='deliveries__rider_i_4847be_idx',
            old_name='deliveries__rider_status_idx',
        ),
    ]
