# Generated by Django 4.2.23 on 2025-07-13 00:35

from django.db import migrations


def add_delivery_locations(apps, schema_editor):
    DeliveryLocation = apps.get_model('deliveries', 'DeliveryLocation')
    
    # Create Bolt Delivery location
    DeliveryLocation.objects.get_or_create(
        name='Bolt Delivery',
        defaults={
            'fee': 0.00,
            'is_active': True
        }
    )
    
    # Create WIX Delivery location
    DeliveryLocation.objects.get_or_create(
        name='WIX Delivery',
        defaults={
            'fee': 0.00,
            'is_active': True
        }
    )


def remove_delivery_locations(apps, schema_editor):
    DeliveryLocation = apps.get_model('deliveries', 'DeliveryLocation')
    DeliveryLocation.objects.filter(name__in=['Bolt Delivery', 'WIX Delivery']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_alter_orderassignment_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_delivery_locations, remove_delivery_locations),
    ]
