# Generated by Django 4.2.23

from django.db import migrations


def remove_wix_delivery_location(apps, schema_editor):
    DeliveryLocation = apps.get_model('deliveries', 'DeliveryLocation')
    # Delete WIX Delivery location
    DeliveryLocation.objects.filter(name='WIX Delivery').delete()


def add_wix_delivery_location(apps, schema_editor):
    DeliveryLocation = apps.get_model('deliveries', 'DeliveryLocation')
    # Re-create WIX Delivery location for rollback
    DeliveryLocation.objects.get_or_create(
        name='WIX Delivery',
        defaults={
            'fee': 0.00,
            'is_active': True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_add_bolt_wix_delivery_locations'),
    ]

    operations = [
        migrations.RunPython(remove_wix_delivery_location, add_wix_delivery_location),
    ]
