# Generated by Django 4.2.23 on 2025-07-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_remove_deliveryrider_rating'),
        ('deliveries', '0009_remove_wix_delivery_location'),
    ]

    operations = [
    ]
