# Generated by Django 4.2.23 on 2025-07-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_merge_20250719_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryrider',
            options={'ordering': ['current_orders', 'name']},
        ),
    ]
